export class GameSummary {
  gameId: number;
  adjustmentsDay: string;
  adjustmentsSpan: number;
  adjustmentsTime: string;
  administrators: any[];
  assignmentMethod: string;
  assignments: any[];
  blindAdministrators: boolean;
  concurrentGamesLimit: number;
  currentYear: number;
  deadlineType: string;
  displayAsAdmin: boolean;
  finalReadinessCheck: boolean;
  gameName: string;
  gameStatus: string;
  gameTimeZone: number;
  hiddenGame: boolean;
  nmrToleranceAdjustments: boolean | null;
  nmrToleranceOrders: boolean | null;
  nmrToleranceRetreats: boolean | null;
  nmrToleranceTotal: number;
  nominationsDay: string;
  nominationsSpan: number;
  nominationsTime: string;
  observeDst: boolean;
  ordersDay: string;
  ordersSpan: number;
  ordersTime: string;
  partialRosterStart: boolean;
  players: number;
  countries: number;
  privateGame: boolean;
  retreatsDay: string;
  retreatsSpan: number;
  retreatsTime: string;
  rules: any[];
  startTime: Date;
  stylizedStartYear: number;
  timeCreated: Date;
  turn1Timing: string;
  voteDelayCount: number | null;
  voteDelayDisplayCount: number | null;
  voteDelayDisplayPercent: number | null;
  voteDelayEnabled: boolean;
  voteDelayLock: number | null;
  voteDelayPercent: number | null;
  votesDay: string;
  votesSpan: number;
  votesTime: string;
  nominationTiming: string;
  nominationYear: number;
  automaticAssignments: boolean;
  ratingLimitsEnabled: boolean;
  funMin: number;
  funMax: number;
  skillMin: number;
  skillMax: number;

  constructor(gameFromDb: any, localTimeZoneName: string) {
    this.gameId = 0;
    this.adjustmentsDay = 'string';
    this.adjustmentsSpan = 0;
    this.adjustmentsTime = 'string';
    this.administrators = [];
    this.assignmentMethod = 'string';
    this.assignments = [];
    this.blindAdministrators = false;
    this.concurrentGamesLimit = 0;
    this.currentYear = 0;
    this.deadlineType = 'string';
    this.displayAsAdmin = false;
    this.finalReadinessCheck = false;
    this.gameName = 'string';
    this.gameStatus = 'string';
    this.gameTimeZone = 0;
    this.hiddenGame = false;
    this.nmrToleranceAdjustments = false;
    this.nmrToleranceOrders = false;
    this.nmrToleranceRetreats = false;
    this.nmrToleranceTotal = 0;
    this.nominationsDay = 'string';
    this.nominationsSpan = 0;
    this.nominationsTime = 'string';
    this.observeDst = false;
    this.ordersDay = 'string';
    this.ordersSpan = 0;
    this.ordersTime = 'string';
    this.partialRosterStart = false;
    this.players = 0;
    this.countries = 0;
    this.privateGame = false;
    this.retreatsDay = 'string';
    this.retreatsSpan = 0;
    this.retreatsTime = 'string';
    this.rules = [];
    this.startTime = new Date();
    this.stylizedStartYear = 0;
    this.timeCreated = new Date();
    this.turn1Timing = 'string';
    this.voteDelayCount = 0;
    this.voteDelayDisplayCount = 0;
    this.voteDelayDisplayPercent = 0;
    this.voteDelayEnabled = false;
    this.voteDelayLock = 0;
    this.voteDelayPercent = 0;
    this.votesDay = 'string';
    this.votesSpan = 0;
    this.votesTime = 'string';
    this.nominationTiming = 'string';
    this.nominationYear = 0;
    this.automaticAssignments = false;
    this.ratingLimitsEnabled = false;
    this.funMin = 0;
    this.funMax = 0;
    this.skillMin = 0;
    this.skillMax = 0;
  }
}